import './globals.scss';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import styles from './layout.module.scss';
import Header from '@/Components/Header/Header';
import { Footer } from '@/Components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className={styles.main}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
